### ISSUE TITLE
如何使用辅助工具中的[待讨论]翻译

### ISSUE THREAD

**Issue by voidsand** [miaowm5/RMMV-F1#109]
角色生成器—>导出窗口—>Import[导出]中的这句话：
Loads a base image from a file and inserts a newly made image.

首先个人认为角色生成器翻译成人物生成器可能更好一些，角色是指我们所扮演的角色Actor，属于人物Character的一种，敌人也属于人物，而这个生成器可以生产的不仅限于角色。

下面来说说这句话，这里的base image其实指的是之前制作好的素材图（官方的或者自己之前做好的）。以人物头像导出窗口为例：当人物头像导出窗口载入之前制作好的人物头像素材图之后，它会把你当前设计的人物头像图片插入其中。标准的人物头像素材图中最多可容纳8个头像，所以这样做其实会覆盖掉一个原有的头像，也就是说用你当前做的这个头像替换掉了素材图中的一个头像。然后再点击导出就可以生成你自定义的新版人物头像素材图。（从基础素材图变成了自定义素材图）这句话其实想描述的就是这个功能。
所以我给出的翻译是：从文件中导入一张待修改的基础素材图，并将当前制作的新素材插入其中，（以备之后将其导出为作者自定义的素材图）。

我翻译的可以能不太好，但这个功能就是这个意思，希望对你们有所帮助。
我觉得文档里有些功能介绍需要翻译者自己先理解之后再加以润色，不然看的人比较难以理解这个功能的真正用途。
最后非常感谢你们的辛勤劳动，让更多热爱RM的国人能够有机会学习它。

**Comment by miaowm5** [comment]
感谢你的建议！：）
@RyanBernX

**Comment by RyanBernX** [comment]
多谢你的建议，因为暂时没有MV所以有些新功能不是很了解，就采用你的翻译吧！
