### ISSUE TITLE
【翻译反馈】动画切片 (img/animations)

### ISSUE THREAD

**Issue by ghost** [miaowm5/RMMV-F1#130]
总感觉翻译为“技能动画”会更合适些

**Comment by miaowm5** [comment]
因为动画并不只会在使用技能时播放，而是在所有播放动画的场合都会用到
并且这个素材的功能是将动画的各个关键帧作为切片单独切出来合并到一张图片上

使用技能动画这个翻译可能会产生误解

**Comment by ghost** [comment]
感觉“切片”的概念有些难以理解

**Comment by miaowm5** [comment]
那么你觉得应该翻译成什么比较合适呢？
动画素材？
动画元件？

**Comment by ghost** [comment]
还是保留切片吧，但是可以把弹出的详细信息附加“动画元件”吗（如果有弹出提示框的话）
还有“权重”，在弹出框里面说明这是优先级

**Comment by miaowm5** [comment]
弹出框是什么……？
