### ISSUE TITLE
01_10_03 ~ 01_10_05.html

### ISSUE THREAD

**Issue by RyanBernX** [miaowm5/RMMV-F1#136]
认领，话说01_10_02还没搞定？已经六天了……

**Comment by miaowm5** [comment]
@molingyu 话说01_10_02还没搞定？已经六天了……

**Comment by shitake2333** [comment]
呃呃 这几天有点事情耽搁了一下。非常抱歉。
对了这个该怎么翻译的好，总觉的好别扭。。。。
The variable calculated in [Variable] will change will change based on the value before the operation, method of calculation, and the operand.

**Comment by RyanBernX** [comment]
意译即可。[Variable（变量）]的计算结果取决于该变量计算前的值，计算的方法，操作数。
