### ISSUE TITLE
01_10_13.html 翻译讨论

### ISSUE THREAD

**Issue by shitake2333** [miaowm5/RMMV-F1#146]
Pan
Set the pan (-100 to 100). The majority of the sound comes out of the left speaker when this is a negative value, and more on the right when set to a positive value.

这个Pan是什么鬼QAQ
看解释像是调节左右声道来产生立体声效果之类的东西。。。。

**Comment by RyanBernX** [comment]
Pan已经讨论过了啊，就是声场定位。可以考虑我的这个翻译：
设置声场定位（-100 ~ 100）。如果为负数，则声音主要从左耳机传来，如果为正数，则声音主要从右耳机传来。

**Comment by shitake2333** [comment]
啊 有点印象结果没找到 囧

**Comment by RyanBernX** [comment]
刚才查了一下，speaker翻译成“扬声器”更准确一些。
