### ISSUE TITLE
纠错: 将游戏打包为Android程序

### ISSUE THREAD

**Issue by ghost** [miaowm5/RMMV-F1#161]
用同样的方法确认你是否搭建成功,打开CMD，输入ant --version，回车，出现版本信息则表示你搭建成功。

->

用同样的方法确认你是否搭建成功,打开CMD，输入ant -version，回车，出现版本信息则表示你搭建成功。

**Comment by taroxd** [comment]
这种情况建议给 pull request 而不是 issue...

**Comment by ghost** [comment]
get, 还没仔细阅读规则, 只是看到就马上发消息了, 谢谢指出

**Comment by miaowm5** [comment]
我看了三遍才发现哪里不同…… :joy:
