### ISSUE TITLE
01.08.09 discuss

### ISSUE THREAD

**Issue by RyanBernX** [miaowm5/RMMV-F1#165]
[Additive] -- display in a whiter color
[Multiply] -- display in a darker color
[Screnn] -- display in a brighter color
这里whiter和brighter都可以翻译为“更亮的颜色”，两种模式有无区别？
另外[Multiply]是翻译成乘法吗，我记得RGSS1里面是减法来着。

**Comment by miaowm5** [comment]
Multiply 正片叠底
Screnn 滤色

Multiply 翻译成乘法看起来不合适…… OTL

**Comment by RyanBernX** [comment]
所以，第一个和第三个的区别是什么？

**Comment by miaowm5** [comment]
A 代表下面图层的颜色值；
B 代表上面图层的颜色值；
C 代表混合图层的颜色值；

## Multiply 正片叠底

C=(A×B)/255

该效果将两层像素的标准色彩值（基于0..1之间）相乘后输出
其效果可以形容成：两个幻灯片叠加在一起然后放映，
透射光需要分别通过这两个幻灯片，从而被削弱了两次。

## Screen 滤色

C=255-(A反相×B反相)/255

该模式和上一个模式刚好相反，
上下层像素的标准色彩值反相后相乘后输出，
输出结果比两者的像素值都将要亮
（就好像两台投影机分别对其中一个图层进行投影后，然后投射到同一个屏幕上）。
从右边公式中我们可以看出，如果两个图层反相后，采用Multiply模式混合，
则将和对这两个图层采用 Screen模式混合后反相的结果完全一样。

……其实我也不知道该怎么解释，按照更白和更亮来理解应该就可以了

**Comment by RyanBernX** [comment]
That's it.
Please close now.
