### ISSUE TITLE
创建名词对照表

### ISSUE THREAD

**Issue by winkidney** [miaowm5/RMMV-F1#48]
可以delay，需要校对的时候再来做

**Comment by shitake2333** [comment]
确实。。。好多类之间都有同名/同效果/同解释的方法或属性。应该保持翻译的一致。
另外我想吐槽一下句号的问题。原版有些部分是有句号有些部分是没有句号。我看了下翻译也是有的没有的有。我这边是短句什么的都有加句号 。这个是怎么处理一下QAQ
