### ISSUE TITLE
关于跳转链接是否需要翻译的问题

### ISSUE THREAD

**Issue by miaowm5** [miaowm5/RMMV-F1#49]
例如类似 03_47.html（https://github.com/miaowm5/RMMV-F1/blob/da1378ff02571610c6c0fcb8fd662f839cd3587f/page/03_47.html#）里40行中的部分：

原文：The array of MoveCommand(跳转链接) data.
翻译：由 移动路线指令(跳转链接) 数据组成的数组。

关于这里的 MoveCommand

我的想法是，MoveCommand 和前代的RMVA不同，并不是一个类，而是一段纯粹的json数据，保留原始名字没有什么意义，因此将名字MoveCommand也翻译巍了，用中文说明了即将跳转到的页面包含的内容。
这种想法是否有错（例如是否能够通过原文的 MoveCommand 获取某些信息）？

@taroxd

**Comment by winkidney** [comment]
我觉得这种名词第一次出现就统一为如下格式：
中文翻译（英文原词）
后面再根据这个出一个对照表即可。
不知意下如何？

**Comment by miaowm5** [comment]
如果单纯为了看的话，我感觉 英文原词（中文翻译） 这样会更好？

**Comment by winkidney** [comment]
有道理，有些词使用英文比较易于理解：）

**Comment by miaowm5** [comment]
不过我个人还是更倾向于不保留英文原词，只留下一个统一的中文翻译这样的

**Comment by winkidney** [comment]
有一些我觉得可以保留
1. UI名（button，menu的名字）
2. 类名，变量名这类

**Comment by miaowm5** [comment]
由于JS本身对类的支持吃翔，所以基本上除了几个静态类以外，剩下的虽然标题写着XX类，实际上却是个匿名的 json ，例如例子中这个跳转链接就是一个栗子
唔我再来@一下
@taroxd

**Comment by taroxd** [comment]
我只是想用英文表示，这个单词是指一种数据类型，不是指这个词本意

<del>单纯为了看的话，英文帮助文档比中文的舒服多了</del>

**Comment by taroxd** [comment]
而且这帮助文档残缺得逼我去看源码。

比如 Sprite#z 属性会在 Tilemap 里给 children 排序用到，**然而 z 属性在 F1 里根本没有提到**！
比如 TilingSprite 的 width 和 height 属性必须设置才能显示出来。而且 TilingSprite 的构造函数里，即使传入一个 Bitmap，也不会自动帮你设置好这个，简直坑死人。

总体来说，我的感觉是事件部分完全不需要F1，而脚本部分的F1写得太坑（应该是从源代码中生成的）

<del>更加坚定了我偷懒不参加翻译的决心</del>
