### ISSUE TITLE
window说明

### ISSUE THREAD

**Issue by shitake2333** [miaowm5/RMMV-F1#50]
关于downArrowVisible的翻译，具体说明可查看6R的帖子
http://rm.66rpg.com/forum.php?mod=viewthread&tid=384555&page=2#lastpost
18楼

**Comment by miaowm5** [comment]
文档的错误，其实其他地方还有挺多的
我的做法是，保留原文但是注释掉，翻译的时候按照自己的理解进行修正。
哦对了，顺便还会给原文的class加一个呵呵

**Comment by shitake2333** [comment]
噗，我没注释。
还有如bitmap的blt，原版的解释有点模糊。我是按照VA的去做的解释。

**Comment by miaowm5** [comment]
有改动的话个人建议保留原文
改动比较大的话建议发个issue说明一下
