### ISSUE TITLE
关于其他组也在汉化RMMV F1的事情

### ISSUE THREAD

**Issue by miaowm5** [miaowm5/RMMV-F1#55]
之前已经知道有其他组也在汉化RMMV F1，

刚刚看到了他们放出的翻译预览：http://www.gormmv.com/
感觉部分章节的翻译质量堪忧，是否要将那边的翻译并入？

**Comment by shitake2333** [comment]
首先，对方貌似并没有翻译出多少的样子【也有可能是没放出来。反正据说的前60丝毫不见踪影】
其次，质量我就不想吐槽了。【员工福利什么鬼】
如果要并入，就得专门有人做校对。不然我是不放心直接放进来的。【虽然我的质量也很鬼就是了】

**Comment by RyanBern32767** [comment]
个人意见：放弃这部分，单干
