### ISSUE TITLE
JS库用语规范讨论

### ISSUE THREAD

**Issue by miaowm5** [miaowm5/RMMV-F1#73]
如果有任何意见建议请回复：

另见：游戏用语规范部分 https://github.com/miaowm5/RMMV-F1/issues/81

<h3>当前规范</h3>

<b>以下内容直接翻译：</b>
JS Library - JS库
Parameters - 参数
Methods - 方法
Properties - 属性
Returns - 返回值
callback function - 回调函数
XX object -  XX对象
[read-only] - [只读属性]
url - 地址
static class - 静态类
x coordinate -  X 坐标
y coordinate -  Y 坐标
Item Index - 索引
browser - 浏览器
video - 视频
screen - 画面
blend mode - 混合模式
renderer - 渲染器
frame - 帧
frame - 框架
alias - 别名
child - 子对象

<b>以下内容采用形如 “stage（场景）” 的，保留原词的方式翻译：</b>
bitmap - 位图
stage - 场景

<b>以下内容不翻译：</b>
canvas
CSS
Graphics
Bitmap

**Comment by lhy-pku** [comment]
rb
frame的翻译不要定死，因为有些frame要翻译成[框架]。
另外，child 可以统一成子对象。

**Comment by taroxd** [comment]
说句和JS库无关的，建议你们讲好 Armor 是护甲还是防具

**Comment by miaowm5** [comment]
反正最后都要统一修一遍……
