### ISSUE TITLE
2015.10.25 19：41修正完成

### ISSUE THREAD

**Issue by miaowm5** [miaowm5/RMMV-F1#75]
https://github.com/miaowm5/RMMV-F1/commit/6ace2d872ba0953b02d047ab42d3692bf9ecd469
taroxd：ADD后面多了一个点。前面的空格不必要。
https://github.com/miaowm5/RMMV-F1/commit/056643ba81853cfdf85c6fb4683fbd9f0d0b24eb
taroxd ：Google Chrome 中间会加 - 吗？
http://rm.66rpg.com/forum.php?mod=redirect&goto=findpost&ptid=384555&pid=2641585
死伤殆尽：
挑个小错，资料集-素材规格-图块-A组-c
自动元件的图像上，如果右下角（8, 8）的位置是透明的话，该自动元件会被判定为森林类元件。森林类元件拥有流体属性时，在图中包含右下角和左下角边界线的八种图块上，行走图不会有半透明处理
原文是"bush element"，是“灌木丛要素”或者按照既往的翻译，“草木繁茂处属性”

**Comment by MonkeyJuice** [comment]
Comment 测试
