### ISSUE TITLE
游戏用语规范讨论

### ISSUE THREAD

**Issue by miaowm5** [miaowm5/RMMV-F1#81]
如果有任何意见建议请回复：

另见：JS库用语规范部分 https://github.com/miaowm5/RMMV-F1/issues/73

<h3>当前规范</h3>

<b>以下内容直接翻译：</b>
Android - 安卓
Maps - 地图
Region - 区域
Editor - 编辑器
plugins - 插件脚本
Database - 数据库
Side-view Battle - 横版战斗
Front-View Battle - 纵版战斗
Skill Types - 技能类型
Magic Skills - 魔法技能
Battler - 战斗图

<b>以下内容采用形如 “stage（场景）” 的，保留原词的方式翻译：</b>

<b>以下内容不翻译：</b>
RPG Maker MV
HTML5
Windows
Mac OS X
iOS
HP
MP
TP

<b>以下内容翻译待讨论：</b>
State: Motion
State: Overlay

**Comment by shitake2333** [comment]
我想问 HP MP TP SP这些如何翻译？还是保留英文？

**Comment by taroxd** [comment]
保留英文就好了吧

**Comment by miaowm5** [comment]
SP 是什么？
@molingyu

**Comment by taroxd** [comment]
Project：工程？项目？
Item：物品？道具？
Armor：护甲？防具？

**Comment by miaowm5** [comment]
慢慢来…………

用语规范是不是改建Wiki比较合适？

**Comment by shitake2333** [comment]
我是尽量保留VA的用语。。。。
