### ISSUE TITLE
总翻译进度统计

### ISSUE THREAD

**Issue by shitake2333** [miaowm5/RMMV-F1#93]
粗略统计了下已翻译过的部分，方便认领时选择章节。

总体进度：（90/133）

RPG Maker MV部分
初识RPG Maker MV（10/10）
准备开始制作你的游戏（1/1）
基本编辑器控制（1/1）
菜单栏（1/1）
如何使用辅助工具（1/1）
开始你的游戏（1/1）
地图（1/4）
数据库（0/17）
事件（4/4）
事件指令（3/18）
资料集（8/10）

JS库部分（59/59）全部翻译达成，开始第一轮校订。

**Comment by miaowm5** [comment]
直接点击网页列表，查看commit 说明为 creat 的文件不就行了
